### ISSUE TITLE
Path separator issues on remote hosts

### ISSUE THREAD

**Issue by alexandruavadanii** [mondersky/tabscolor-vscode#25]
vscode has an odd way of handling paths in certain scenarios, especially when connected to a remote host (using remote-ssh, probably in WSL too).

For example, if the local host uses Windows paths and the remote host uses Linux:
- paths for file on the remote will naturally have the Linux path separator, e.g. `/home/user/path`;
- paths for files on the local machine will be displayed in the UI (we are mostly interested in the "title" argument for CSS matching here) using Linux paths also, e.g. `/C:/Users/user/path` - I find this unexpected;

Using the developer tools, we can inspect the injected CSS and adjust it a bit for testing (the context is as described above, local machine running Windows, connected to a Linux remote host - but editing a local file):

```css
/* does not work */
.tab[title*="C:\\Users\\alav\\AppData\\Roaming\\Code - Insiders\\User\\settings.json" i] {
    background-color: red !important;
    opacity: 1.0;
}

/* works */
.tab[title*="/C:/Users/alav/AppData/Roaming/Code - Insiders/User/settings.json" i] {
    background-color: green !important;
    opacity: 1.0;
}
```

Currently, the extension just takes the `fsPath` reported by vscode for documents at face value (considering it should contain the right path separator) and does very little processing on it (doubling the '\\' for Win32 paths, replacing the homedir for Linux).

Ideally, we would detect the right path separator at runtime and adjust any paths to use that.
However, I find that tricky to do in vscode, or at least it was tricky to cover all corner cases the last time I looked at it.

A more brutal approach, but imo guaranteed to work would be to add CSS filtering for both paths, something like this:

```css
.tab[title$="/some/path" i],
.tab[title$="\\some\\path" i]
```

While I can't force anyone to like this method, I implemented it locally and it does seem to work, so if you'd like a pull request for doubling all the filters, let me know.
